<a href="https://colab.research.google.com/github/Pritam1729/Predicting-Costumer-Churn/blob/main/Predicting_Costumer_churn_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import pylab as pl
import numpy as np
import scipy.optimize as opt
from sklearn import preprocessing
%matplotlib inline 
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork/labs/Module%203/data/ChurnData.csv")
display(df)

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0      11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1      33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2      23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3      38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4       7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   
..      ...   ...      ...     ...  ...     ...    ...       ...       ...   
195    55.0  44.0     24.0    83.0  1.0    23.0    0.0       1.0       0.0   
196    34.0  23.0      3.0    24.0  1.0     7.0    0.0       1.0       0.0   
197     6.0  32.0     10.0    47.0  1.0    10.0    0.0       1.0       0.0   
198    24.0  30.0      0.0    25.0  4.0     5.0    0.0       1.0       1.0   
199    61.0  50.0     16.0   190.0  2.0    22.0    1.0       1.0       1.0   

     longmon  ...  pager  internet  callwait  confer  ebill  loglong  logtoll  \
0       4.40  ...    1.0       0.0       1.0     1.0    0.0    1.482    3.033   
1       9.45  ...    0.0       0.0       0.0     0.0    0.0    2.246    3.240   
2       6.30  ...    0.0       0.0       0.0     1.0    0.0    1.841    3.240   
3       6.05  ...    1.0       1.0       1.0     1.0    1.0    1.800    3.807   
4       7.10  ...    0.0       0.0       1.0     1.0    0.0    1.960    3.091   
..       ...  ...    ...       ...       ...     ...    ...      ...      ...   
195    17.35  ...    0.0       0.0       0.0     1.0    0.0    2.854    3.199   
196     6.00  ...    0.0       0.0       1.0     1.0    0.0    1.792    3.332   
197     3.85  ...    0.0       0.0       1.0     1.0    0.0    1.348    3.168   
198     8.70  ...    1.0       1.0       1.0     1.0    1.0    2.163    3.866   
199    16.85  ...    0.0       1.0       0.0     0.0    1.0    2.824    3.240   

     lninc  custcat  churn  
0    4.913      4.0    1.0  
1    3.497      1.0    1.0  
2    3.401      3.0    0.0  
3    4.331      4.0    0.0  
4    4.382      3.0    0.0  
..     ...      ...    ...  
195  4.419      3.0    0.0  
196  3.178      3.0    0.0  
197  3.850      3.0    0.0  
198  3.219      4.0    1.0  
199  5.247      2.0    0.0  

[200 rows x 28 columns]

In [ ]:
dff=df[["ed","employ","equip","callcard","wireless"]]
display(dff)




ed  employ  equip  callcard  wireless
0    5.0     5.0    0.0       1.0       1.0
1    2.0     0.0    0.0       0.0       0.0
2    1.0     2.0    0.0       0.0       0.0
3    2.0    10.0    1.0       1.0       1.0
4    2.0    15.0    0.0       1.0       0.0
..   ...     ...    ...       ...       ...
195  1.0    23.0    0.0       1.0       0.0
196  1.0     7.0    0.0       1.0       0.0
197  1.0    10.0    0.0       1.0       0.0
198  4.0     5.0    0.0       1.0       1.0
199  2.0    22.0    1.0       1.0       1.0

[200 rows x 5 columns]

In [ ]:
churn_dff = dff[["ed","employ","equip","callcard","wireless"]]
churn_dff['employ'] = churn_dff['employ'].astype('int')
churn_dff.head(10)

ed  employ  equip  callcard  wireless
0  5.0       5    0.0       1.0       1.0
1  2.0       0    0.0       0.0       0.0
2  1.0       2    0.0       0.0       0.0
3  2.0      10    1.0       1.0       1.0
4  2.0      15    0.0       1.0       0.0
5  1.0      24    0.0       1.0       0.0
6  2.0       8    1.0       1.0       1.0
7  2.0       2    0.0       0.0       0.0
8  2.0      21    0.0       1.0       0.0
9  4.0      19    0.0       1.0       0.0

In [ ]:
X = np.asanyarray(churn_dff[["ed","employ","equip","callcard","wireless"]])
X[0:5]

array([[ 5.,  5.,  0.,  1.,  1.],
       [ 2.,  0.,  0.,  0.,  0.],
       [ 1.,  2.,  0.,  0.,  0.],
       [ 2., 10.,  1.,  1.,  1.],
       [ 2., 15.,  0.,  1.,  0.]])

In [ ]:
y = np.asanyarray(df['churn'])
y [0:5]

array([1., 1., 0., 0., 0.])

In [ ]:
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)
X[0:5]

array([[ 1.6961288 , -0.58477841, -0.85972695,  0.64686916,  1.56469673],
       [-0.6433592 , -1.14437497, -0.85972695, -1.54590766, -0.63910148],
       [-1.42318853, -0.92053635, -0.85972695, -1.54590766, -0.63910148],
       [-0.6433592 , -0.02518185,  1.16316   ,  0.64686916,  1.56469673],
       [-0.6433592 ,  0.53441472, -0.85972695,  0.64686916, -0.63910148]])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (160, 5) (160,)
Test set: (40, 5) (40,)


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)
LR

LogisticRegression(C=0.01, solver='liblinear')

In [ ]:
yhat = LR.predict(X_test)
yhat

array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1.,
       1., 1., 0., 1., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 1.])

In [ ]:
yhat_prob = LR.predict_proba(X_test)
yhat_prob

array([[0.56628588, 0.43371412],
       [0.56512867, 0.43487133],
       [0.5692309 , 0.4307691 ],
       [0.66540031, 0.33459969],
       [0.53373132, 0.46626868],
       [0.64105839, 0.35894161],
       [0.5218807 , 0.4781193 ],
       [0.58920219, 0.41079781],
       [0.45274683, 0.54725317],
       [0.56448138, 0.43551862],
       [0.48367103, 0.51632897],
       [0.5377661 , 0.4622339 ],
       [0.61409713, 0.38590287],
       [0.45624138, 0.54375862],
       [0.70304928, 0.29695072],
       [0.53491585, 0.46508415],
       [0.45624138, 0.54375862],
       [0.44860984, 0.55139016],
       [0.44229245, 0.55770755],
       [0.60276889, 0.39723111],
       [0.49305494, 0.50694506],
       [0.46039879, 0.53960121],
       [0.64369144, 0.35630856],
       [0.48080925, 0.51919075],
       [0.50260065, 0.49739935],
       [0.67474799, 0.32525201],
       [0.48015564, 0.51984436],
       [0.4885077 , 0.5114923 ],
       [0.54358463, 0.45641537],
       [0.66853111, 0.33146889],
       [0.

In [ ]:
confusion_matrix(y_test, yhat)

array([[18,  7],
       [ 9,  6]])

In [ ]:
churn_dff = df[['pager','internet','callwait','ebill','callcard']]
churn_dff.head(10)

pager  internet  callwait  ebill  callcard
0    1.0       0.0       1.0    0.0       1.0
1    0.0       0.0       0.0    0.0       0.0
2    0.0       0.0       0.0    0.0       0.0
3    1.0       1.0       1.0    1.0       1.0
4    0.0       0.0       1.0    0.0       1.0
5    0.0       0.0       0.0    0.0       1.0
6    0.0       1.0       1.0    1.0       1.0
7    0.0       0.0       0.0    0.0       0.0
8    0.0       0.0       1.0    0.0       1.0
9    0.0       1.0       1.0    1.0       1.0

In [ ]:
X = np.asanyarray(churn_dff[['pager','internet','callwait','ebill','callcard']])
X[0:5]

array([[1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [0., 0., 1., 0., 1.]])

In [ ]:
y = np.asanyarray(df['churn'])
y [0:5]

array([1., 1., 0., 0., 0.])

In [ ]:
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)
X[0:5]

array([[ 1.62368828, -0.88640526,  1.0944415 , -0.88640526,  0.64686916],
       [-0.61588176, -0.88640526, -0.91370804, -0.88640526, -1.54590766],
       [-0.61588176, -0.88640526, -0.91370804, -0.88640526, -1.54590766],
       [ 1.62368828,  1.12815215,  1.0944415 ,  1.12815215,  0.64686916],
       [-0.61588176, -0.88640526,  1.0944415 , -0.88640526,  0.64686916]])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (160, 5) (160,)
Test set: (40, 5) (40,)


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)
LR

LogisticRegression(C=0.01, solver='liblinear')

In [ ]:
yhat = LR.predict(X_test)
yhat

array([0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 0., 0., 0.,
       0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 1.])

In [ ]:
yhat_prob = LR.predict_proba(X_test)
yhat_prob

array([[0.53928481, 0.46071519],
       [0.60518235, 0.39481765],
       [0.57264854, 0.42735146],
       [0.53981368, 0.46018632],
       [0.57264854, 0.42735146],
       [0.65449157, 0.34550843],
       [0.50453379, 0.49546621],
       [0.65290319, 0.34709681],
       [0.4529614 , 0.5470386 ],
       [0.48643532, 0.51356468],
       [0.48643532, 0.51356468],
       [0.53928481, 0.46071519],
       [0.65290319, 0.34709681],
       [0.4529614 , 0.5470386 ],
       [0.65290319, 0.34709681],
       [0.65449157, 0.34550843],
       [0.51969   , 0.48031   ],
       [0.60634961, 0.39365039],
       [0.4529614 , 0.5470386 ],
       [0.60518235, 0.39481765],
       [0.52022135, 0.47977865],
       [0.48643532, 0.51356468],
       [0.65449157, 0.34550843],
       [0.48643532, 0.51356468],
       [0.48643532, 0.51356468],
       [0.65449157, 0.34550843],
       [0.50277975, 0.49722025],
       [0.53754104, 0.46245896],
       [0.57264854, 0.42735146],
       [0.65449157, 0.34550843],
       [0.

In [ ]:
confusion_matrix(y_test, yhat)

array([[20,  5],
       [10,  5]])

In [ ]:
churn_dff = df[['internet','callwait','ebill','callcard']]
churn_dff.head(10)

X = np.asanyarray(churn_dff[['internet','callwait','ebill','callcard']])
X[0:5]

y = np.asanyarray(df['churn'])
y [0:5]

from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)
X[0:5]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)
LR

yhat = LR.predict(X_test)
yhat

yhat_prob = LR.predict_proba(X_test)
yhat_prob

confusion_matrix(y_test, yhat)





Train set: (160, 4) (160,)
Test set: (40, 4) (40,)


array([[24,  1],
       [11,  4]])

In [ ]:
churn_dff = df[['internet','logtoll','ebill','callcard']]
churn_dff.head(10)

X = np.asanyarray(churn_dff[['internet','logtoll','ebill','callcard']])
X[0:5]

y = np.asanyarray(df['churn'])
y [0:5]

from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)
X[0:5]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)
LR

yhat = LR.predict(X_test)
yhat

yhat_prob = LR.predict_proba(X_test)
yhat_prob

confusion_matrix(y_test, yhat)





Train set: (160, 4) (160,)
Test set: (40, 4) (40,)


array([[24,  1],
       [10,  5]])

accuracy of 72.5 %

In [ ]:
churn_dff = df[['internet','logtoll','age','ebill',]]
churn_dff.head(10)

X = np.asanyarray(churn_dff[['internet','logtoll','ebill','age']])
X[0:5]

y = np.asanyarray(df['churn'])
y [0:5]

from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)
X[0:5]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)
LR

yhat = LR.predict(X_test)
yhat

yhat_prob = LR.predict_proba(X_test)
yhat_prob

confusion_matrix(y_test, yhat)





Train set: (160, 4) (160,)
Test set: (40, 4) (40,)


array([[21,  4],
       [ 9,  6]])

accuracy of 67.5%

In [ ]:
churn_dff = df[['internet','lninc','logtoll','ebill','callwait']]
churn_dff.head(10)

X = np.asanyarray(churn_dff[['internet','lninc','logtoll','ebill','callwait']])
X[0:5]

y = np.asanyarray(df['churn'])
y [0:5]

from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)
X[0:5]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)
LR

yhat = LR.predict(X_test)
yhat

yhat_prob = LR.predict_proba(X_test)
yhat_prob

confusion_matrix(y_test, yhat)





Train set: (160, 5) (160,)
Test set: (40, 5) (40,)


array([[21,  4],
       [10,  5]])